export const FEATURES = {
  // 🏠 Pages principales (desenvolvimento - todas ativas)
  ENABLE_ACCUEIL: true,
  ENABLE_PROFIL: false, 
  ENABLE_TEST_UI: true,
  
  // ⚙️ Paramètres Globaux
  ENABLE_PARAMETRES_GLOBAL: true,
  ENABLE_ENTITES: true,
  ENABLE_TIERS: true,
  ENABLE_TYPE_TIERS: true,
  ENABLE_TYPE_FACTURE: true,
  ENABLE_IMPORT_CA_DETAIL: true,
  ENABLE_IMPORT_FACTURE: true,
  ENABLE_IMPORT_TIERS: true,
  ENABLE_IMPORT_GLOBAL: true,
  
  // 🏦 Module Banques
  ENABLE_BANQUES: true,
  ENABLE_PARAMETRES_BANQUE: true,
  ENABLE_COMPTES_BANCAIRE: true,
  ENABLE_MODE_PAIEMENT: true,
  ENABLE_IMPORT_FORMAT: true,
  ENABLE_IMPORT_RELEVES_BRUT: true,
  ENABLE_ECRITURE_BANCAIRE: true,
  
  // 👥 Module Employés
  ENABLE_EMPLOYES: true,
  ENABLE_PARAMETRES_EMPLOYES: true,
  ENABLE_BUDGET_RH: true,
  ENABLE_FICHE_PERSONNEL: true,
  ENABLE_MES_EMPLOYES: true,
  ENABLE_PARAM_GENERAUX: true,
  ENABLE_PARAM_SOUS_CATEGORIES_RH: true,
  ENABLE_TYPE_CONTRAT: true,
  ENABLE_TYPE_FONCTION: true,
  
  // 💰 Module Finances
  ENABLE_FINANCES: true,
  ENABLE_PARAMETRES_FINANCES: true,
  ENABLE_SAISIE_BUDGET_ANNUEL: true,
  ENABLE_SUIVI_CA_REEL: true,
  ENABLE_SUIVI_CA_BUDGET: true,
  ENABLE_TEST_DATA_TABLE_FULL: true,
  ENABLE_EDIT_FACTURE_ACHAT: true,
  ENABLE_MES_FACTURES: true,
  ENABLE_FERMETURE_CAISSE: true,
  ENABLE_CA_TYPE_SERVICE: true,
  ENABLE_SOUS_CATEGORIE_FLUX: true,
  ENABLE_NATURE_FLUX: true,
  ENABLE_PARAM_JOURS: true,
  ENABLE_CATEGORIE_FLUX: true,
  
  // 🧪 Features avancées
  ENABLE_TRANSLATION: true,
  SHOW_ADVANCED_MENU: true,
  ENABLE_STATS_PAGE: true,
}